version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    FRONTEND_REPO: 022499003794.dkr.ecr.us-east-1.amazonaws.com/bhavesh-frontend-repo
    BACKEND_REPO: 022499003794.dkr.ecr.us-east-1.amazonaws.com/bhavesh-backend-repo
    ECS_CLUSTER: bhavesh-pipeline-container
    ECS_SERVICE: bhavesh-pipeline-task-service-oqt9ntdm
    TASK_DEFINITION: bhavesh-pipeline-task

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${FRONTEND_REPO%/*}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - FRONTEND_IMAGE_TAG=${COMMIT_HASH:=latest}
      - BACKEND_IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building Docker images...
      - docker build -t $FRONTEND_REPO:$FRONTEND_IMAGE_TAG -f frontend/Dockerfile frontend
      - docker build -t $BACKEND_REPO:$BACKEND_IMAGE_TAG -f backend/Dockerfile backend

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $FRONTEND_REPO:$FRONTEND_IMAGE_TAG
      - docker push $BACKEND_REPO:$BACKEND_IMAGE_TAG

      - echo Registering new ECS task definition revision...
      - |
        FRONTEND_IMAGE="$FRONTEND_REPO:$FRONTEND_IMAGE_TAG"
        BACKEND_IMAGE="$BACKEND_REPO:$BACKEND_IMAGE_TAG"

        # Get current task definition JSON
        TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEFINITION)

        # Update container images by matching container names
        NEW_TASK_DEF=$(echo $TASK_DEF | \
          jq --arg FRONTEND_IMAGE "$FRONTEND_IMAGE" \
             --arg BACKEND_IMAGE "$BACKEND_IMAGE" \
          '.taskDefinition |
           del(.status, .requiresAttributes, .compatibilities, .taskDefinitionArn, .revision) |
           .containerDefinitions |= map(
             if .name | test("frontend"; "i") then
               .image = $FRONTEND_IMAGE
             elif .name | test("backend"; "i") then
               .image = $BACKEND_IMAGE
             else
               .
             end
           )')

        echo "$NEW_TASK_DEF" > new-task-def.json
        aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - echo Updating ECS service to use new task definition revision...
      - LATEST_REVISION=$(aws ecs describe-task-definition --task-definition $TASK_DEFINITION | jq '.taskDefinition.revision')
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition ${TASK_DEFINITION}:${LATEST_REVISION} --region $AWS_REGION

artifacts:
  files:
    - '**/*'
